/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as CompanyAboutRouteImport } from './routes/company.about'
import { Route as CompanyCareersRouteImport } from './routes/company.careers'
import { Route as CompanyPressRouteImport } from './routes/company.press'
import { Route as CompanyResearchRouteImport } from './routes/company.research'
import { Route as ProductBrixPhRouteImport } from './routes/product.brix-ph'
import { Route as ProductCropHealthRouteImport } from './routes/product.crop-health'
import { Route as ProductSeedQualityRouteImport } from './routes/product.seed-quality'
import { Route as ProductSoilDiagnosticsRouteImport } from './routes/product.soil-diagnostics'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyAboutRoute = CompanyAboutRouteImport.update({
  id: '/company/about',
  path: '/company/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyCareersRoute = CompanyCareersRouteImport.update({
  id: '/company/careers',
  path: '/company/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyPressRoute = CompanyPressRouteImport.update({
  id: '/company/press',
  path: '/company/press',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyResearchRoute = CompanyResearchRouteImport.update({
  id: '/company/research',
  path: '/company/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductBrixPhRoute = ProductBrixPhRouteImport.update({
  id: '/product/brix-ph',
  path: '/product/brix-ph',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductCropHealthRoute = ProductCropHealthRouteImport.update({
  id: '/product/crop-health',
  path: '/product/crop-health',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSeedQualityRoute = ProductSeedQualityRouteImport.update({
  id: '/product/seed-quality',
  path: '/product/seed-quality',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSoilDiagnosticsRoute = ProductSoilDiagnosticsRouteImport.update({
  id: '/product/soil-diagnostics',
  path: '/product/soil-diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/reset-password': typeof ResetPasswordRoute
  '/company/about': typeof CompanyAboutRoute
  '/company/careers': typeof CompanyCareersRoute
  '/company/press': typeof CompanyPressRoute
  '/company/research': typeof CompanyResearchRoute
  '/product/brix-ph': typeof ProductBrixPhRoute
  '/product/crop-health': typeof ProductCropHealthRoute
  '/product/seed-quality': typeof ProductSeedQualityRoute
  '/product/soil-diagnostics': typeof ProductSoilDiagnosticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/reset-password': typeof ResetPasswordRoute
  '/company/about': typeof CompanyAboutRoute
  '/company/careers': typeof CompanyCareersRoute
  '/company/press': typeof CompanyPressRoute
  '/company/research': typeof CompanyResearchRoute
  '/product/brix-ph': typeof ProductBrixPhRoute
  '/product/crop-health': typeof ProductCropHealthRoute
  '/product/seed-quality': typeof ProductSeedQualityRoute
  '/product/soil-diagnostics': typeof ProductSoilDiagnosticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/reset-password': typeof ResetPasswordRoute
  '/company/about': typeof CompanyAboutRoute
  '/company/careers': typeof CompanyCareersRoute
  '/company/press': typeof CompanyPressRoute
  '/company/research': typeof CompanyResearchRoute
  '/product/brix-ph': typeof ProductBrixPhRoute
  '/product/crop-health': typeof ProductCropHealthRoute
  '/product/seed-quality': typeof ProductSeedQualityRoute
  '/product/soil-diagnostics': typeof ProductSoilDiagnosticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyze'
    | '/auth'
    | '/dashboard'
    | '/reset-password'
    | '/company/about'
    | '/company/careers'
    | '/company/press'
    | '/company/research'
    | '/product/brix-ph'
    | '/product/crop-health'
    | '/product/seed-quality'
    | '/product/soil-diagnostics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyze'
    | '/auth'
    | '/dashboard'
    | '/reset-password'
    | '/company/about'
    | '/company/careers'
    | '/company/press'
    | '/company/research'
    | '/product/brix-ph'
    | '/product/crop-health'
    | '/product/seed-quality'
    | '/product/soil-diagnostics'
  id:
    | '__root__'
    | '/'
    | '/analyze'
    | '/auth'
    | '/dashboard'
    | '/reset-password'
    | '/company/about'
    | '/company/careers'
    | '/company/press'
    | '/company/research'
    | '/product/brix-ph'
    | '/product/crop-health'
    | '/product/seed-quality'
    | '/product/soil-diagnostics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzeRoute: typeof AnalyzeRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  CompanyAboutRoute: typeof CompanyAboutRoute
  CompanyCareersRoute: typeof CompanyCareersRoute
  CompanyPressRoute: typeof CompanyPressRoute
  CompanyResearchRoute: typeof CompanyResearchRoute
  ProductBrixPhRoute: typeof ProductBrixPhRoute
  ProductCropHealthRoute: typeof ProductCropHealthRoute
  ProductSeedQualityRoute: typeof ProductSeedQualityRoute
  ProductSoilDiagnosticsRoute: typeof ProductSoilDiagnosticsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/about': {
      id: '/company/about'
      path: '/company/about'
      fullPath: '/company/about'
      preLoaderRoute: typeof CompanyAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/careers': {
      id: '/company/careers'
      path: '/company/careers'
      fullPath: '/company/careers'
      preLoaderRoute: typeof CompanyCareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/press': {
      id: '/company/press'
      path: '/company/press'
      fullPath: '/company/press'
      preLoaderRoute: typeof CompanyPressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/research': {
      id: '/company/research'
      path: '/company/research'
      fullPath: '/company/research'
      preLoaderRoute: typeof CompanyResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/brix-ph': {
      id: '/product/brix-ph'
      path: '/product/brix-ph'
      fullPath: '/product/brix-ph'
      preLoaderRoute: typeof ProductBrixPhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/crop-health': {
      id: '/product/crop-health'
      path: '/product/crop-health'
      fullPath: '/product/crop-health'
      preLoaderRoute: typeof ProductCropHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/seed-quality': {
      id: '/product/seed-quality'
      path: '/product/seed-quality'
      fullPath: '/product/seed-quality'
      preLoaderRoute: typeof ProductSeedQualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/soil-diagnostics': {
      id: '/product/soil-diagnostics'
      path: '/product/soil-diagnostics'
      fullPath: '/product/soil-diagnostics'
      preLoaderRoute: typeof ProductSoilDiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzeRoute: AnalyzeRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  CompanyAboutRoute: CompanyAboutRoute,
  CompanyCareersRoute: CompanyCareersRoute,
  CompanyPressRoute: CompanyPressRoute,
  CompanyResearchRoute: CompanyResearchRoute,
  ProductBrixPhRoute: ProductBrixPhRoute,
  ProductCropHealthRoute: ProductCropHealthRoute,
  ProductSeedQualityRoute: ProductSeedQualityRoute,
  ProductSoilDiagnosticsRoute: ProductSoilDiagnosticsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
